# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db2d0021cb374ffa26503e94826f9fa63908739772f32d021ff7a29c3a65949104bfc85b0d4bd6017f91934c585167f1602be2bd67e5e7b0e59967b76c21e441

test:
  secret_key_base: 5397ea82727c048c110fc4e7ed6b9220026722ab7d7e83eb508757501219de6500d15e5d58c8523c17b391065e1b096afd7e27e42f2df1d6b2f262edd90cea2a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
